import { anchorIdField } from '@/fields/anchorIdField'

import type { Block } from 'payload'

export const Skills: Block = {
  slug: 'skills',
  interfaceName: 'SkillsBlock',
  fields: [
    anchorIdField('skills'),
    {
      name: 'title',
      type: 'text',
      required: true,
      label: 'Section Title',
      defaultValue: 'Technical Skills',
    },
    {
      name: 'codeLabel',
      type: 'text',
      label: 'Code Label',
      defaultValue: '// 04 — skills',
      admin: {
        description: 'Badge mono affiché au-dessus du titre (ex: // 04 — skills)',
      },
    },
    {
      name: 'subtitle',
      type: 'text',
      label: 'Subtitle',
    },
    {
      name: 'description',
      type: 'textarea',
      label: 'Description',
    },
    {
      name: 'skills',
      type: 'array',
      label: 'Skills',
      required: true,
      minRows: 1,
      defaultValue: [
        { name: 'JavaScript / TypeScript', level: 'expert', percentage: 92, category: 'frontend', color: 'blue' },
        { name: 'Next.js & React', level: 'expert', percentage: 93, category: 'frontend', color: 'purple' },
        { name: 'Tailwind CSS', level: 'advanced', percentage: 88, category: 'frontend', color: 'teal' },
        { name: 'Node.js', level: 'advanced', percentage: 85, category: 'backend', color: 'green' },
        { name: 'Python', level: 'advanced', percentage: 75, category: 'backend', color: 'green' },
        { name: 'MongoDB', level: 'advanced', percentage: 85, category: 'database', color: 'green' },
        { name: 'PostgreSQL / MySQL', level: 'intermediate', percentage: 72, category: 'database', color: 'blue' },
        { name: 'Git / GitLab / GitHub', level: 'expert', percentage: 90, category: 'devops', color: 'orange' },
        { name: 'Docker', level: 'intermediate', percentage: 65, category: 'devops', color: 'blue' },
        { name: 'Payload CMS', level: 'expert', percentage: 95, category: 'other', color: 'purple' },
        { name: 'Strapi', level: 'advanced', percentage: 82, category: 'other', color: 'green' },
        { name: 'React Native', level: 'advanced', percentage: 78, category: 'mobile', color: 'indigo' },
        { name: 'n8n (AI workflows)', level: 'advanced', percentage: 78, category: 'other', color: 'indigo' },
      ],
      fields: [
        {
          name: 'name',
          type: 'text',
          required: true,
          label: 'Skill Name',
        },
        {
          name: 'level',
          type: 'select',
          label: 'Proficiency Level',
          options: [
            { label: 'Beginner', value: 'beginner' },
            { label: 'Intermediate', value: 'intermediate' },
            { label: 'Advanced', value: 'advanced' },
            { label: 'Expert', value: 'expert' },
          ],
          defaultValue: 'intermediate',
        },
        {
          name: 'percentage',
          type: 'number',
          label: 'Proficiency Percentage',
          min: 0,
          max: 100,
          defaultValue: 75,
        },
        {
          name: 'icon',
          type: 'upload',
          relationTo: 'media',
          label: 'Skill Icon',
        },
        {
          name: 'category',
          type: 'select',
          label: 'Category',
          options: [
            { label: 'Frontend', value: 'frontend' },
            { label: 'Backend', value: 'backend' },
            { label: 'Database', value: 'database' },
            { label: 'DevOps', value: 'devops' },
            { label: 'Design', value: 'design' },
            { label: 'Mobile', value: 'mobile' },
            { label: 'Other', value: 'other' },
          ],
          defaultValue: 'other',
        },
        {
          name: 'color',
          type: 'select',
          label: 'Color Theme',
          options: [
            { label: 'Blue', value: 'blue' },
            { label: 'Purple', value: 'purple' },
            { label: 'Green', value: 'green' },
            { label: 'Orange', value: 'orange' },
            { label: 'Red', value: 'red' },
            { label: 'Pink', value: 'pink' },
            { label: 'Teal', value: 'teal' },
            { label: 'Indigo', value: 'indigo' },
          ],
          defaultValue: 'blue',
        },
      ],
    },
    {
      name: 'displayStyle',
      type: 'select',
      label: 'Display Style',
      options: [
        { label: 'Grid Cards (3 columns)', value: 'grid' },
        { label: 'Grid Cards (4 columns)', value: 'grid4' },
        { label: 'Progress Bars', value: 'progress' },
        { label: 'Circular Progress', value: 'circular' },
        { label: 'Interactive Chart', value: 'chart' },
        { label: 'Scroll Carousel', value: 'cardSwap' },
      ],
      defaultValue: 'grid',
    },
    {
      name: 'animationStyle',
      type: 'select',
      label: 'Animation Style',
      options: [
        { label: 'Fade In', value: 'fadeIn' },
        { label: 'Slide Up', value: 'slideUp' },
        { label: 'Scale', value: 'scale' },
        { label: 'Stagger', value: 'stagger' },
      ],
      defaultValue: 'fadeIn',
    },
    {
      name: 'showParticles',
      type: 'checkbox',
      label: 'Show Particle Animation',
      defaultValue: false,
    },
    {
      name: 'backgroundImage',
      type: 'upload',
      relationTo: 'media',
      label: 'Background Image',
    },
  ],
}
